---
# File Name: scRNA-Seq-template.yaml
# Created By: hkim and zw
# Created On: 2022-07-20
# Purpose: template configuration for the scRNA-Seq-pipeline

DOC_TYPE: "GLOBAL_CONFIG"
analysis_name: "scRNA-Seq-Template"
working_directory: "my-directory"
files: {
  transcriptome: "/my/path/to/transcriptome/",
  sequencing: [{
    run_id: "runA",
    fastq_1: "runA-1.fastq",
    fastq_2: "runA-2.fastq",
    library_id: "library-1",
    experiment_id: "library-1"
  }
  ]
}
...
---
DOC_TYPE: "RULE_CONFIGS"
rule_name: "CR_fastq_to_counts"
parameters: {
  ncells: 10000
}
resources: {
  walltime: "02:30:00",
  nodes: 1,
  processors_per_node: 4,
  total_memory: 8000,
  total_memory_gb: 8
}
